import { db } from "@workspace/db";
import {
  busRoutesTable,
  busStopsTable,
  routeStopsTable,
  busFrequencyTable,
} from "@workspace/db";

// ─── BUS TYPE COLORS (Namma BMTC official color scheme) ───────────────────────
// Ordinary (Red/Cream):  #DC2626
// Vajra AC (Blue):       #2563EB
// Volvo Premium (Green): #16A34A
// Airport Shuttle (Pink):#DB2777
// Metro Feeder (Teal):   #0891B2
// Night Service (Purple):#7C3AED
// ──────────────────────────────────────────────────────────────────────────────

const stops: Array<{ id: string; name: string; lat: number; lng: number; zone: string }> = [
  // ─── CENTRAL ─────────────────────────────────────────────────────────────────
  { id: "majestic", name: "Majestic (KBS)", lat: 12.9766, lng: 77.5714, zone: "Central" },
  { id: "shivajinagar", name: "Shivajinagar", lat: 12.9850, lng: 77.5980, zone: "Central" },
  { id: "mg-road", name: "MG Road", lat: 12.9756, lng: 77.6093, zone: "Central" },
  { id: "brigade-road", name: "Brigade Road", lat: 12.9735, lng: 77.6130, zone: "Central" },
  { id: "city-market", name: "City Market (KR Market)", lat: 12.9634, lng: 77.5753, zone: "Central" },
  { id: "corporation", name: "Corporation Circle", lat: 12.9807, lng: 77.5930, zone: "Central" },
  { id: "richmond-circle", name: "Richmond Circle", lat: 12.9642, lng: 77.5999, zone: "Central" },
  { id: "cubbon-park", name: "Cubbon Park", lat: 12.9763, lng: 77.5930, zone: "Central" },
  { id: "ulsoor", name: "Ulsoor", lat: 12.9818, lng: 77.6185, zone: "Central" },
  { id: "fraser-town", name: "Fraser Town", lat: 12.9949, lng: 77.6191, zone: "Central" },

  // ─── NORTH ───────────────────────────────────────────────────────────────────
  { id: "mekhri-circle", name: "Mekhri Circle", lat: 13.0028, lng: 77.5744, zone: "North" },
  { id: "hebbal", name: "Hebbal", lat: 13.0351, lng: 77.5940, zone: "North" },
  { id: "yelahanka", name: "Yelahanka", lat: 13.1010, lng: 77.5963, zone: "North" },
  { id: "yelahanka-old", name: "Yelahanka Old Town", lat: 13.1058, lng: 77.5836, zone: "North" },
  { id: "rt-nagar", name: "RT Nagar", lat: 13.0210, lng: 77.5960, zone: "North" },
  { id: "thanisandra", name: "Thanisandra", lat: 13.0528, lng: 77.6218, zone: "North" },
  { id: "vidyaranyapura", name: "Vidyaranyapura", lat: 13.0690, lng: 77.5548, zone: "North" },
  { id: "jalahalli", name: "Jalahalli", lat: 13.0490, lng: 77.5270, zone: "North" },
  { id: "peenya", name: "Peenya", lat: 13.0280, lng: 77.5180, zone: "North" },
  { id: "nagawara", name: "Nagawara", lat: 13.0430, lng: 77.6126, zone: "North" },
  { id: "kalyan-nagar", name: "Kalyan Nagar", lat: 13.0290, lng: 77.6380, zone: "North" },
  { id: "hennur-road", name: "Hennur Road", lat: 13.0368, lng: 77.6275, zone: "North" },
  { id: "bagalur-road", name: "Bagalur Road", lat: 13.1350, lng: 77.6450, zone: "North" },
  { id: "doddaballapur-road", name: "Doddaballapur Road", lat: 13.0726, lng: 77.5432, zone: "North" },
  { id: "devanahalli", name: "Devanahalli", lat: 13.2468, lng: 77.7120, zone: "North" },
  { id: "kial", name: "Kempegowda Intl Airport (KIAL)", lat: 13.1986, lng: 77.7066, zone: "North" },

  // ─── WEST ────────────────────────────────────────────────────────────────────
  { id: "rajajinagar", name: "Rajajinagar", lat: 12.9910, lng: 77.5530, zone: "West" },
  { id: "yeshwanthpur", name: "Yeshwantpur", lat: 13.0230, lng: 77.5360, zone: "West" },
  { id: "malleshwaram", name: "Malleshwaram", lat: 13.0010, lng: 77.5630, zone: "West" },
  { id: "vijayanagar", name: "Vijayanagar", lat: 12.9720, lng: 77.5350, zone: "West" },
  { id: "kengeri", name: "Kengeri", lat: 12.9124, lng: 77.4820, zone: "West" },
  { id: "mysore-road", name: "Mysore Road (Satellite Town)", lat: 12.9560, lng: 77.5080, zone: "West" },
  { id: "rajarajeshwari-nagar", name: "Rajarajeshwari Nagar", lat: 12.9200, lng: 77.5060, zone: "West" },
  { id: "nagarbhavi", name: "Nagarbhavi", lat: 12.9670, lng: 77.5140, zone: "West" },
  { id: "nayandahalli", name: "Nayandahalli", lat: 12.9580, lng: 77.5280, zone: "West" },
  { id: "pattanagere", name: "Pattanagere", lat: 12.9150, lng: 77.4990, zone: "West" },
  { id: "hesaraghatta", name: "Hesaraghatta Road", lat: 13.0760, lng: 77.5028, zone: "West" },

  // ─── SOUTH ───────────────────────────────────────────────────────────────────
  { id: "jayanagar", name: "Jayanagar 4th Block", lat: 12.9308, lng: 77.5836, zone: "South" },
  { id: "basavanagudi", name: "Basavanagudi", lat: 12.9428, lng: 77.5742, zone: "South" },
  { id: "jp-nagar", name: "JP Nagar", lat: 12.9062, lng: 77.5826, zone: "South" },
  { id: "banashankari", name: "Banashankari", lat: 12.9260, lng: 77.5470, zone: "South" },
  { id: "btm-layout", name: "BTM Layout", lat: 12.9165, lng: 77.6101, zone: "South" },
  { id: "silk-board", name: "Silk Board Junction", lat: 12.9170, lng: 77.6233, zone: "South" },
  { id: "hsr-layout", name: "HSR Layout", lat: 12.9116, lng: 77.6474, zone: "South" },
  { id: "electronic-city", name: "Electronic City", lat: 12.8399, lng: 77.6770, zone: "South" },
  { id: "bommanahalli", name: "Bommanahalli", lat: 12.8973, lng: 77.6222, zone: "South" },
  { id: "bannerghatta-road", name: "Bannerghatta Road", lat: 12.8883, lng: 77.5975, zone: "South" },
  { id: "gottigere", name: "Gottigere", lat: 12.8698, lng: 77.5977, zone: "South" },
  { id: "uttarahalli", name: "Uttarahalli", lat: 12.9028, lng: 77.5366, zone: "South" },
  { id: "chandapura", name: "Chandapura", lat: 12.8100, lng: 77.6840, zone: "South" },
  { id: "electronic-city-ph2", name: "Electronic City Phase 2", lat: 12.8278, lng: 77.6741, zone: "South" },
  { id: "konanakunte", name: "Konanakunte", lat: 12.8884, lng: 77.5776, zone: "South" },
  { id: "sarjapur-road", name: "Sarjapur Road", lat: 12.9091, lng: 77.6806, zone: "South" },
  { id: "bidadi", name: "Bidadi", lat: 12.7930, lng: 77.3980, zone: "South" },
  { id: "mico-layout", name: "MICO Layout", lat: 12.9072, lng: 77.5980, zone: "South" },

  // ─── EAST ────────────────────────────────────────────────────────────────────
  { id: "indiranagar", name: "Indiranagar 100ft Rd", lat: 12.9784, lng: 77.6408, zone: "East" },
  { id: "domlur", name: "Domlur", lat: 12.9614, lng: 77.6378, zone: "East" },
  { id: "old-airport-road", name: "Old Airport Road", lat: 12.9796, lng: 77.6493, zone: "East" },
  { id: "koramangala", name: "Koramangala", lat: 12.9352, lng: 77.6245, zone: "East" },
  { id: "ejipura", name: "Ejipura", lat: 12.9477, lng: 77.6296, zone: "East" },
  { id: "marathahalli", name: "Marathahalli", lat: 12.9591, lng: 77.6974, zone: "East" },
  { id: "kr-puram", name: "KR Puram", lat: 13.0055, lng: 77.6960, zone: "East" },
  { id: "whitefield", name: "Whitefield", lat: 12.9698, lng: 77.7500, zone: "East" },
  { id: "tin-factory", name: "Tin Factory", lat: 13.0043, lng: 77.6691, zone: "East" },
  { id: "baiyappanahalli", name: "Baiyappanahalli", lat: 12.9914, lng: 77.6578, zone: "East" },
  { id: "outer-ring-road", name: "Outer Ring Road", lat: 12.9560, lng: 77.7100, zone: "East" },
  { id: "varthur", name: "Varthur", lat: 12.9388, lng: 77.7434, zone: "East" },
  { id: "kadugodi", name: "Kadugodi", lat: 12.9834, lng: 77.7572, zone: "East" },
  { id: "hope-farm", name: "Hope Farm Junction", lat: 12.9774, lng: 77.7399, zone: "East" },
  { id: "haralur-road", name: "Haralur Road", lat: 12.9138, lng: 77.6786, zone: "East" },
  { id: "carmelaram", name: "Carmelaram", lat: 12.9070, lng: 77.7086, zone: "East" },
  { id: "brookefield", name: "Brookefield", lat: 12.9660, lng: 77.7306, zone: "East" },
  { id: "kundalahalli", name: "Kundalahalli Gate", lat: 12.9691, lng: 77.7214, zone: "East" },
  { id: "panathur", name: "Panathur Road", lat: 12.9453, lng: 77.7141, zone: "East" },

  // ─── HUBS / INTERCHANGES ─────────────────────────────────────────────────────
  { id: "airport-road", name: "Airport Road", lat: 13.0500, lng: 77.6100, zone: "North" },
  { id: "hebbal-flyover", name: "Hebbal Flyover", lat: 13.0408, lng: 77.5905, zone: "North" },
  { id: "kempapura", name: "Kempapura", lat: 13.0630, lng: 77.5800, zone: "North" },
];

type BusType = "Ordinary" | "Vajra" | "Volvo" | "Airport" | "MetroFeeder" | "Night";

interface RouteData {
  id: string;
  name: string;
  number: string;
  from: string;
  to: string;
  color: string;
  busType: BusType;
  depot: string;
  lastBusTime: string;
  distance: number;
  stops: string[];
}

const routes: RouteData[] = [
  // ════════════════════════════════════════════════════════════════════════════
  // ORDINARY ROUTES (Red)
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "1",
    number: "1",
    name: "KBS - Jalahalli Cross",
    from: "Majestic (KBS)",
    to: "Jalahalli",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Jalahalli",
    lastBusTime: "22:00",
    distance: 18.2,
    stops: ["majestic", "rajajinagar", "yeshwanthpur", "peenya", "jalahalli"],
  },
  {
    id: "2",
    number: "2",
    name: "KBS - Yelahanka",
    from: "Majestic (KBS)",
    to: "Yelahanka",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Yelahanka",
    lastBusTime: "22:30",
    distance: 15.8,
    stops: ["majestic", "malleshwaram", "mekhri-circle", "rt-nagar", "yelahanka"],
  },
  {
    id: "6",
    number: "6",
    name: "KBS - Hesaraghatta Road",
    from: "Majestic (KBS)",
    to: "Hesaraghatta",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Peenya",
    lastBusTime: "21:30",
    distance: 22.0,
    stops: ["majestic", "rajajinagar", "yeshwanthpur", "peenya", "jalahalli", "hesaraghatta"],
  },
  {
    id: "8",
    number: "8",
    name: "KBS - Vidyaranyapura",
    from: "Majestic (KBS)",
    to: "Vidyaranyapura",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Jalahalli",
    lastBusTime: "22:00",
    distance: 16.5,
    stops: ["majestic", "malleshwaram", "mekhri-circle", "rt-nagar", "vidyaranyapura"],
  },
  {
    id: "10",
    number: "10",
    name: "KBS - Domlur via HAL",
    from: "Majestic (KBS)",
    to: "Domlur",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Shivajinagar",
    lastBusTime: "22:15",
    distance: 12.0,
    stops: ["majestic", "corporation", "mg-road", "ulsoor", "old-airport-road", "domlur"],
  },
  {
    id: "12a",
    number: "12A",
    name: "KBS - Indiranagar",
    from: "Majestic (KBS)",
    to: "Indiranagar",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Shivajinagar",
    lastBusTime: "22:30",
    distance: 10.5,
    stops: ["majestic", "corporation", "mg-road", "ulsoor", "indiranagar"],
  },
  {
    id: "17a",
    number: "17A",
    name: "KBS - KR Puram via Old Airport Rd",
    from: "Majestic (KBS)",
    to: "KR Puram",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "KR Puram",
    lastBusTime: "22:00",
    distance: 19.0,
    stops: ["majestic", "shivajinagar", "old-airport-road", "indiranagar", "tin-factory", "baiyappanahalli", "kr-puram"],
  },
  {
    id: "25",
    number: "25",
    name: "KBS - Jayanagar",
    from: "Majestic (KBS)",
    to: "Jayanagar 4th Block",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Banashankari",
    lastBusTime: "22:30",
    distance: 8.5,
    stops: ["majestic", "city-market", "basavanagudi", "jayanagar"],
  },
  {
    id: "29e",
    number: "29E",
    name: "KBS - Bannerghatta Road",
    from: "Majestic (KBS)",
    to: "Bannerghatta Road",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Banashankari",
    lastBusTime: "21:45",
    distance: 20.0,
    stops: ["majestic", "city-market", "jayanagar", "banashankari", "bannerghatta-road", "gottigere"],
  },
  {
    id: "33",
    number: "33",
    name: "KBS - Electronic City",
    from: "Majestic (KBS)",
    to: "Electronic City",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Electronic City",
    lastBusTime: "22:00",
    distance: 28.0,
    stops: ["majestic", "city-market", "jayanagar", "btm-layout", "silk-board", "bommanahalli", "electronic-city"],
  },
  {
    id: "37",
    number: "37",
    name: "KBS - HSR Layout via Koramangala",
    from: "Majestic (KBS)",
    to: "HSR Layout",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Banashankari",
    lastBusTime: "22:00",
    distance: 17.5,
    stops: ["majestic", "corporation", "mg-road", "koramangala", "ejipura", "btm-layout", "silk-board", "hsr-layout"],
  },
  {
    id: "38",
    number: "38",
    name: "KBS - Silk Board via Jayanagar",
    from: "Majestic (KBS)",
    to: "Silk Board Junction",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Banashankari",
    lastBusTime: "22:30",
    distance: 15.2,
    stops: ["majestic", "city-market", "jayanagar", "btm-layout", "silk-board"],
  },
  {
    id: "41",
    number: "41",
    name: "KBS - Whitefield Direct",
    from: "Majestic (KBS)",
    to: "Whitefield",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "KR Puram",
    lastBusTime: "22:00",
    distance: 31.0,
    stops: ["majestic", "shivajinagar", "ulsoor", "indiranagar", "old-airport-road", "marathahalli", "kundalahalli", "whitefield"],
  },
  {
    id: "47",
    number: "47",
    name: "KBS - Bannerghatta via Jayanagar",
    from: "Majestic (KBS)",
    to: "Gottigere",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Banashankari",
    lastBusTime: "21:30",
    distance: 23.0,
    stops: ["majestic", "city-market", "jayanagar", "jp-nagar", "banashankari", "bannerghatta-road", "gottigere"],
  },
  {
    id: "91",
    number: "91",
    name: "KBS - Banashankari",
    from: "Majestic (KBS)",
    to: "Banashankari",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Banashankari",
    lastBusTime: "22:30",
    distance: 11.0,
    stops: ["majestic", "city-market", "basavanagudi", "jp-nagar", "banashankari"],
  },
  {
    id: "97",
    number: "97",
    name: "KBS - Uttarahalli",
    from: "Majestic (KBS)",
    to: "Uttarahalli",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Kengeri",
    lastBusTime: "22:00",
    distance: 16.0,
    stops: ["majestic", "vijayanagar", "banashankari", "jp-nagar", "uttarahalli"],
  },
  {
    id: "100",
    number: "100",
    name: "KBS - Chandapura",
    from: "Majestic (KBS)",
    to: "Chandapura",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Electronic City",
    lastBusTime: "21:30",
    distance: 33.0,
    stops: ["majestic", "jayanagar", "silk-board", "hsr-layout", "bommanahalli", "electronic-city", "electronic-city-ph2", "chandapura"],
  },
  {
    id: "150a",
    number: "150A",
    name: "KBS - Whitefield via Domlur",
    from: "Majestic (KBS)",
    to: "Whitefield",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "KR Puram",
    lastBusTime: "22:00",
    distance: 32.5,
    stops: ["majestic", "corporation", "domlur", "indiranagar", "old-airport-road", "marathahalli", "brookefield", "whitefield"],
  },
  {
    id: "201r",
    number: "201R",
    name: "Majestic - Electronic City",
    from: "Majestic (KBS)",
    to: "Electronic City",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Electronic City",
    lastBusTime: "22:00",
    distance: 27.0,
    stops: ["majestic", "jayanagar", "basavanagudi", "btm-layout", "silk-board", "bommanahalli", "electronic-city"],
  },
  {
    id: "225",
    number: "225",
    name: "Jayanagar - Whitefield",
    from: "Jayanagar 4th Block",
    to: "Whitefield",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "KR Puram",
    lastBusTime: "21:45",
    distance: 24.0,
    stops: ["jayanagar", "koramangala", "ejipura", "domlur", "indiranagar", "old-airport-road", "marathahalli", "outer-ring-road", "whitefield"],
  },
  {
    id: "240",
    number: "240",
    name: "Banashankari - Marathahalli",
    from: "Banashankari",
    to: "Marathahalli",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Banashankari",
    lastBusTime: "22:00",
    distance: 22.0,
    stops: ["banashankari", "btm-layout", "koramangala", "ejipura", "domlur", "old-airport-road", "marathahalli"],
  },
  {
    id: "252",
    number: "252",
    name: "JP Nagar - Shivajinagar",
    from: "JP Nagar",
    to: "Shivajinagar",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Shivajinagar",
    lastBusTime: "21:30",
    distance: 19.5,
    stops: ["jp-nagar", "banashankari", "basavanagudi", "jayanagar", "richmond-circle", "mg-road", "shivajinagar"],
  },
  {
    id: "255",
    number: "255",
    name: "JP Nagar - Marathahalli via BTM",
    from: "JP Nagar",
    to: "Marathahalli",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Banashankari",
    lastBusTime: "21:45",
    distance: 21.0,
    stops: ["jp-nagar", "btm-layout", "silk-board", "koramangala", "domlur", "old-airport-road", "marathahalli"],
  },
  {
    id: "273",
    number: "273",
    name: "JP Nagar - Whitefield",
    from: "JP Nagar",
    to: "Whitefield",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "KR Puram",
    lastBusTime: "21:30",
    distance: 30.0,
    stops: ["jp-nagar", "silk-board", "koramangala", "old-airport-road", "marathahalli", "kundalahalli", "whitefield"],
  },
  {
    id: "296",
    number: "296",
    name: "Vijayanagar - KR Puram",
    from: "Vijayanagar",
    to: "KR Puram",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "KR Puram",
    lastBusTime: "22:00",
    distance: 25.0,
    stops: ["vijayanagar", "majestic", "corporation", "mg-road", "ulsoor", "tin-factory", "baiyappanahalli", "kr-puram"],
  },
  {
    id: "300",
    number: "300",
    name: "Shivajinagar - Electronic City",
    from: "Shivajinagar",
    to: "Electronic City",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Electronic City",
    lastBusTime: "22:00",
    distance: 26.0,
    stops: ["shivajinagar", "corporation", "richmond-circle", "koramangala", "btm-layout", "silk-board", "bommanahalli", "electronic-city"],
  },
  {
    id: "313c",
    number: "313C",
    name: "Vijayanagar - Whitefield",
    from: "Vijayanagar",
    to: "Whitefield",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "KR Puram",
    lastBusTime: "22:15",
    distance: 35.0,
    stops: ["vijayanagar", "rajajinagar", "majestic", "mg-road", "indiranagar", "marathahalli", "outer-ring-road", "whitefield"],
  },
  {
    id: "335",
    number: "335",
    name: "Shivajinagar - Mysore Road",
    from: "Shivajinagar",
    to: "Mysore Road",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Kengeri",
    lastBusTime: "22:00",
    distance: 22.0,
    stops: ["shivajinagar", "corporation", "majestic", "vijayanagar", "nayandahalli", "mysore-road"],
  },
  {
    id: "356f",
    number: "356F",
    name: "Silk Board - Whitefield Express",
    from: "Silk Board Junction",
    to: "Whitefield",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "KR Puram",
    lastBusTime: "23:00",
    distance: 22.0,
    stops: ["silk-board", "koramangala", "indiranagar", "old-airport-road", "marathahalli", "outer-ring-road", "whitefield"],
  },
  {
    id: "365",
    number: "365",
    name: "KBS - Sarjapur Road",
    from: "Majestic (KBS)",
    to: "Sarjapur Road",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Electronic City",
    lastBusTime: "21:30",
    distance: 29.0,
    stops: ["majestic", "koramangala", "ejipura", "silk-board", "hsr-layout", "sarjapur-road"],
  },
  {
    id: "400",
    number: "400",
    name: "KBS - Yelahanka Old Town",
    from: "Majestic (KBS)",
    to: "Yelahanka Old Town",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Yelahanka",
    lastBusTime: "22:00",
    distance: 17.0,
    stops: ["majestic", "malleshwaram", "mekhri-circle", "hebbal", "rt-nagar", "yelahanka", "yelahanka-old"],
  },
  {
    id: "401",
    number: "401",
    name: "KR Puram - Majestic",
    from: "KR Puram",
    to: "Majestic (KBS)",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "KR Puram",
    lastBusTime: "21:45",
    distance: 19.0,
    stops: ["kr-puram", "tin-factory", "old-airport-road", "ulsoor", "mg-road", "corporation", "majestic"],
  },
  {
    id: "500d",
    number: "500D",
    name: "Majestic - Yelahanka via Hebbal",
    from: "Majestic (KBS)",
    to: "Yelahanka",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Yelahanka",
    lastBusTime: "22:30",
    distance: 18.5,
    stops: ["majestic", "malleshwaram", "mekhri-circle", "hebbal", "airport-road", "yelahanka"],
  },
  {
    id: "600d",
    number: "600D",
    name: "KBS - Kengeri",
    from: "Majestic (KBS)",
    to: "Kengeri",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Kengeri",
    lastBusTime: "22:15",
    distance: 16.0,
    stops: ["majestic", "vijayanagar", "nayandahalli", "rajarajeshwari-nagar", "pattanagere", "kengeri"],
  },
  {
    id: "600k",
    number: "600K",
    name: "Kengeri - Electronic City",
    from: "Kengeri",
    to: "Electronic City",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Kengeri",
    lastBusTime: "22:00",
    distance: 32.0,
    stops: ["kengeri", "vijayanagar", "banashankari", "jp-nagar", "btm-layout", "hsr-layout", "bommanahalli", "electronic-city"],
  },
  {
    id: "650",
    number: "650",
    name: "KBS - Bidadi",
    from: "Majestic (KBS)",
    to: "Bidadi",
    color: "#DC2626",
    busType: "Ordinary",
    depot: "Kengeri",
    lastBusTime: "21:00",
    distance: 42.0,
    stops: ["majestic", "vijayanagar", "kengeri", "mysore-road", "bidadi"],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // VAJRA AC ROUTES (Blue)
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "v1",
    number: "V-1",
    name: "KBS - Electronic City (Vajra AC)",
    from: "Majestic (KBS)",
    to: "Electronic City",
    color: "#2563EB",
    busType: "Vajra",
    depot: "Electronic City",
    lastBusTime: "23:30",
    distance: 27.0,
    stops: ["majestic", "city-market", "basavanagudi", "jayanagar", "btm-layout", "silk-board", "bommanahalli", "electronic-city"],
  },
  {
    id: "v2",
    number: "V-2",
    name: "KBS - Whitefield (Vajra AC)",
    from: "Majestic (KBS)",
    to: "Whitefield",
    color: "#2563EB",
    busType: "Vajra",
    depot: "KR Puram",
    lastBusTime: "23:30",
    distance: 31.0,
    stops: ["majestic", "corporation", "mg-road", "ulsoor", "indiranagar", "marathahalli", "brookefield", "whitefield"],
  },
  {
    id: "v100",
    number: "V-100",
    name: "KBS - Yelahanka (Vajra AC)",
    from: "Majestic (KBS)",
    to: "Yelahanka",
    color: "#2563EB",
    busType: "Vajra",
    depot: "Yelahanka",
    lastBusTime: "23:00",
    distance: 15.8,
    stops: ["majestic", "malleshwaram", "mekhri-circle", "hebbal", "yelahanka"],
  },
  {
    id: "v300",
    number: "V-300",
    name: "Shivajinagar - Electronic City (Vajra AC)",
    from: "Shivajinagar",
    to: "Electronic City",
    color: "#2563EB",
    busType: "Vajra",
    depot: "Electronic City",
    lastBusTime: "23:00",
    distance: 26.0,
    stops: ["shivajinagar", "mg-road", "koramangala", "btm-layout", "silk-board", "bommanahalli", "electronic-city"],
  },
  {
    id: "v500",
    number: "V-500",
    name: "KBS - Yelahanka via Hebbal (Vajra AC)",
    from: "Majestic (KBS)",
    to: "Yelahanka",
    color: "#2563EB",
    busType: "Vajra",
    depot: "Yelahanka",
    lastBusTime: "23:30",
    distance: 18.5,
    stops: ["majestic", "malleshwaram", "mekhri-circle", "hebbal", "airport-road", "yelahanka"],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // VOLVO PREMIUM AC ROUTES (Green)
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "335e",
    number: "335E",
    name: "Shivajinagar - Mysore Road (Volvo)",
    from: "Shivajinagar",
    to: "Mysore Road",
    color: "#16A34A",
    busType: "Volvo",
    depot: "Kengeri",
    lastBusTime: "23:00",
    distance: 22.0,
    stops: ["shivajinagar", "majestic", "vijayanagar", "nayandahalli", "mysore-road"],
  },
  {
    id: "356e",
    number: "356E",
    name: "Shivajinagar - Whitefield (Volvo)",
    from: "Shivajinagar",
    to: "Whitefield",
    color: "#16A34A",
    busType: "Volvo",
    depot: "KR Puram",
    lastBusTime: "23:30",
    distance: 32.0,
    stops: ["shivajinagar", "ulsoor", "indiranagar", "old-airport-road", "marathahalli", "kundalahalli", "whitefield"],
  },
  {
    id: "500c",
    number: "500C",
    name: "KBS - Yelahanka via Hebbal (Volvo)",
    from: "Majestic (KBS)",
    to: "Yelahanka",
    color: "#16A34A",
    busType: "Volvo",
    depot: "Yelahanka",
    lastBusTime: "23:30",
    distance: 18.5,
    stops: ["majestic", "malleshwaram", "mekhri-circle", "hebbal", "kempapura", "yelahanka"],
  },
  {
    id: "g7v",
    number: "G-7",
    name: "HSR Layout - Electronic City (Volvo)",
    from: "HSR Layout",
    to: "Electronic City",
    color: "#16A34A",
    busType: "Volvo",
    depot: "Electronic City",
    lastBusTime: "22:30",
    distance: 14.0,
    stops: ["hsr-layout", "silk-board", "bommanahalli", "electronic-city"],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // AIRPORT SHUTTLE ROUTES (Pink/Magenta)
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "kia-1",
    number: "KIA-1",
    name: "Domlur - Kempegowda Intl Airport",
    from: "Domlur",
    to: "Kempegowda Intl Airport",
    color: "#DB2777",
    busType: "Airport",
    depot: "Yelahanka",
    lastBusTime: "23:59",
    distance: 36.0,
    stops: ["domlur", "indiranagar", "old-airport-road", "baiyappanahalli", "tin-factory", "hebbal", "hebbal-flyover", "airport-road", "kial"],
  },
  {
    id: "kia-3",
    number: "KIA-3",
    name: "Indiranagar - Kempegowda Intl Airport",
    from: "Indiranagar",
    to: "Kempegowda Intl Airport",
    color: "#DB2777",
    busType: "Airport",
    depot: "Yelahanka",
    lastBusTime: "23:59",
    distance: 34.0,
    stops: ["indiranagar", "old-airport-road", "baiyappanahalli", "kr-puram", "hebbal", "airport-road", "kial"],
  },
  {
    id: "kia-6",
    number: "KIA-6",
    name: "Banashankari - Kempegowda Intl Airport",
    from: "Banashankari",
    to: "Kempegowda Intl Airport",
    color: "#DB2777",
    busType: "Airport",
    depot: "Yelahanka",
    lastBusTime: "23:59",
    distance: 42.0,
    stops: ["banashankari", "jp-nagar", "basavanagudi", "majestic", "mekhri-circle", "hebbal", "airport-road", "kial"],
  },
  {
    id: "kia-8",
    number: "KIA-8",
    name: "Electronic City - Kempegowda Intl Airport",
    from: "Electronic City",
    to: "Kempegowda Intl Airport",
    color: "#DB2777",
    busType: "Airport",
    depot: "Yelahanka",
    lastBusTime: "23:59",
    distance: 54.0,
    stops: ["electronic-city", "bommanahalli", "silk-board", "koramangala", "corporation", "majestic", "mekhri-circle", "hebbal", "airport-road", "kial"],
  },
  {
    id: "kia-9",
    number: "KIA-9",
    name: "Majestic - Kempegowda Intl Airport",
    from: "Majestic (KBS)",
    to: "Kempegowda Intl Airport",
    color: "#DB2777",
    busType: "Airport",
    depot: "Yelahanka",
    lastBusTime: "23:59",
    distance: 38.0,
    stops: ["majestic", "yeshwanthpur", "mekhri-circle", "hebbal", "hebbal-flyover", "airport-road", "devanahalli", "kial"],
  },
  {
    id: "kia-10",
    number: "KIA-10",
    name: "KBS - Airport via Yeshwantpur",
    from: "Majestic (KBS)",
    to: "Kempegowda Intl Airport",
    color: "#DB2777",
    busType: "Airport",
    depot: "Yelahanka",
    lastBusTime: "23:59",
    distance: 40.0,
    stops: ["majestic", "rajajinagar", "yeshwanthpur", "peenya", "doddaballapur-road", "bagalur-road", "devanahalli", "kial"],
  },
  {
    id: "kia-14",
    number: "KIA-14",
    name: "Whitefield - Kempegowda Intl Airport",
    from: "Whitefield",
    to: "Kempegowda Intl Airport",
    color: "#DB2777",
    busType: "Airport",
    depot: "Yelahanka",
    lastBusTime: "23:59",
    distance: 45.0,
    stops: ["whitefield", "kr-puram", "tin-factory", "hebbal", "airport-road", "kial"],
  },
  {
    id: "kia-15",
    number: "KIA-15",
    name: "BTM Layout - Kempegowda Intl Airport",
    from: "BTM Layout",
    to: "Kempegowda Intl Airport",
    color: "#DB2777",
    busType: "Airport",
    depot: "Yelahanka",
    lastBusTime: "23:59",
    distance: 50.0,
    stops: ["btm-layout", "silk-board", "koramangala", "ulsoor", "shivajinagar", "majestic", "mekhri-circle", "hebbal", "airport-road", "kial"],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // METRO FEEDER ROUTES (Teal)
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "mf-6",
    number: "MF-6",
    name: "Baiyappanahalli Metro - Whitefield",
    from: "Baiyappanahalli",
    to: "Whitefield",
    color: "#0891B2",
    busType: "MetroFeeder",
    depot: "KR Puram",
    lastBusTime: "22:30",
    distance: 18.0,
    stops: ["baiyappanahalli", "old-airport-road", "marathahalli", "kundalahalli", "brookefield", "whitefield"],
  },
  {
    id: "mf-10",
    number: "MF-10",
    name: "Rajajinagar Metro - Peenya",
    from: "Rajajinagar",
    to: "Peenya",
    color: "#0891B2",
    busType: "MetroFeeder",
    depot: "Peenya",
    lastBusTime: "22:00",
    distance: 8.0,
    stops: ["rajajinagar", "yeshwanthpur", "peenya"],
  },
  {
    id: "mf-15",
    number: "MF-15",
    name: "MG Road Metro - Koramangala",
    from: "MG Road",
    to: "Koramangala",
    color: "#0891B2",
    busType: "MetroFeeder",
    depot: "Shivajinagar",
    lastBusTime: "22:30",
    distance: 6.0,
    stops: ["mg-road", "richmond-circle", "koramangala"],
  },
  {
    id: "mf-22",
    number: "MF-22",
    name: "Nagawara Metro - Thanisandra",
    from: "Nagawara",
    to: "Thanisandra",
    color: "#0891B2",
    busType: "MetroFeeder",
    depot: "Yelahanka",
    lastBusTime: "22:00",
    distance: 7.0,
    stops: ["nagawara", "kalyan-nagar", "hennur-road", "thanisandra"],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // NIGHT SERVICE ROUTES (Purple)
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: "201n",
    number: "201N",
    name: "KBS - Electronic City (Night Service)",
    from: "Majestic (KBS)",
    to: "Electronic City",
    color: "#7C3AED",
    busType: "Night",
    depot: "Electronic City",
    lastBusTime: "04:00",
    distance: 27.0,
    stops: ["majestic", "jayanagar", "btm-layout", "silk-board", "bommanahalli", "electronic-city"],
  },
  {
    id: "500n",
    number: "500N",
    name: "KBS - Yelahanka (Night Service)",
    from: "Majestic (KBS)",
    to: "Yelahanka",
    color: "#7C3AED",
    busType: "Night",
    depot: "Yelahanka",
    lastBusTime: "04:00",
    distance: 18.5,
    stops: ["majestic", "mekhri-circle", "hebbal", "yelahanka"],
  },
];

type FreqData = {
  weekday: [number, number, number, number];
  weekend: [number, number, number, number];
};

const frequencies: Record<string, FreqData> = {
  // Ordinary — high frequency
  "1":    { weekday: [8, 5, 7, 2], weekend: [5, 4, 5, 1] },
  "2":    { weekday: [7, 4, 6, 2], weekend: [5, 3, 5, 1] },
  "6":    { weekday: [5, 3, 4, 1], weekend: [3, 2, 3, 1] },
  "8":    { weekday: [6, 4, 5, 2], weekend: [4, 3, 4, 1] },
  "10":   { weekday: [8, 5, 7, 2], weekend: [5, 4, 5, 1] },
  "12a":  { weekday: [7, 5, 8, 2], weekend: [5, 4, 6, 1] },
  "17a":  { weekday: [6, 4, 6, 2], weekend: [4, 3, 4, 1] },
  "25":   { weekday: [8, 5, 7, 2], weekend: [5, 4, 5, 1] },
  "29e":  { weekday: [5, 3, 4, 1], weekend: [3, 2, 3, 1] },
  "33":   { weekday: [6, 4, 6, 2], weekend: [4, 3, 4, 1] },
  "37":   { weekday: [5, 3, 5, 2], weekend: [3, 2, 4, 1] },
  "38":   { weekday: [7, 5, 8, 3], weekend: [5, 4, 6, 2] },
  "41":   { weekday: [4, 3, 5, 1], weekend: [3, 2, 3, 1] },
  "47":   { weekday: [5, 3, 4, 1], weekend: [3, 2, 3, 1] },
  "91":   { weekday: [8, 5, 7, 2], weekend: [5, 4, 5, 1] },
  "97":   { weekday: [5, 3, 5, 1], weekend: [3, 2, 3, 1] },
  "100":  { weekday: [3, 2, 3, 1], weekend: [2, 1, 2, 1] },
  "150a": { weekday: [4, 3, 5, 1], weekend: [3, 2, 3, 1] },
  "201r": { weekday: [5, 4, 6, 2], weekend: [3, 3, 4, 1] },
  "225":  { weekday: [4, 3, 5, 1], weekend: [3, 2, 3, 1] },
  "240":  { weekday: [4, 3, 4, 1], weekend: [3, 2, 3, 1] },
  "252":  { weekday: [5, 3, 6, 2], weekend: [4, 3, 4, 1] },
  "255":  { weekday: [4, 3, 5, 1], weekend: [3, 2, 3, 1] },
  "273":  { weekday: [3, 2, 4, 1], weekend: [2, 2, 3, 1] },
  "296":  { weekday: [4, 3, 4, 1], weekend: [3, 2, 3, 1] },
  "300":  { weekday: [5, 4, 6, 2], weekend: [4, 3, 5, 1] },
  "313c": { weekday: [4, 3, 5, 2], weekend: [3, 2, 3, 1] },
  "335":  { weekday: [5, 3, 5, 2], weekend: [4, 3, 4, 1] },
  "356f": { weekday: [6, 3, 7, 2], weekend: [4, 2, 4, 1] },
  "365":  { weekday: [3, 2, 3, 1], weekend: [2, 2, 2, 1] },
  "400":  { weekday: [5, 3, 4, 1], weekend: [3, 2, 3, 1] },
  "401":  { weekday: [7, 5, 8, 3], weekend: [5, 4, 5, 2] },
  "500d": { weekday: [8, 4, 6, 2], weekend: [5, 3, 4, 1] },
  "600d": { weekday: [6, 4, 5, 2], weekend: [4, 3, 4, 1] },
  "600k": { weekday: [4, 3, 5, 2], weekend: [3, 2, 3, 1] },
  "650":  { weekday: [2, 1, 2, 1], weekend: [2, 1, 2, 1] },
  // Vajra — moderate frequency, higher comfort
  "v1":   { weekday: [6, 5, 8, 3], weekend: [4, 4, 6, 2] },
  "v2":   { weekday: [5, 4, 7, 3], weekend: [4, 3, 5, 2] },
  "v100": { weekday: [5, 4, 6, 3], weekend: [4, 3, 5, 2] },
  "v300": { weekday: [5, 4, 7, 3], weekend: [4, 3, 5, 2] },
  "v500": { weekday: [6, 5, 8, 3], weekend: [4, 4, 6, 2] },
  // Volvo — lower frequency, premium
  "335e": { weekday: [3, 2, 4, 1], weekend: [2, 2, 3, 1] },
  "356e": { weekday: [4, 3, 5, 2], weekend: [3, 2, 4, 1] },
  "500c": { weekday: [4, 3, 5, 2], weekend: [3, 2, 4, 1] },
  "g7v":  { weekday: [3, 2, 3, 1], weekend: [2, 2, 2, 1] },
  // Airport — 24/7, high frequency
  "kia-1":  { weekday: [6, 6, 6, 4], weekend: [5, 5, 5, 4] },
  "kia-3":  { weekday: [6, 6, 6, 4], weekend: [5, 5, 5, 4] },
  "kia-6":  { weekday: [5, 5, 5, 3], weekend: [4, 4, 4, 3] },
  "kia-8":  { weekday: [4, 4, 4, 3], weekend: [3, 3, 3, 3] },
  "kia-9":  { weekday: [6, 6, 6, 4], weekend: [6, 5, 6, 4] },
  "kia-10": { weekday: [5, 5, 5, 3], weekend: [4, 4, 4, 3] },
  "kia-14": { weekday: [4, 4, 4, 3], weekend: [3, 3, 3, 3] },
  "kia-15": { weekday: [4, 4, 4, 3], weekend: [3, 3, 3, 3] },
  // Metro Feeders
  "mf-6":  { weekday: [8, 6, 8, 4], weekend: [6, 5, 6, 3] },
  "mf-10": { weekday: [7, 5, 7, 3], weekend: [5, 4, 5, 2] },
  "mf-15": { weekday: [8, 6, 8, 4], weekend: [6, 5, 6, 3] },
  "mf-22": { weekday: [6, 4, 6, 3], weekend: [4, 3, 4, 2] },
  // Night service
  "201n": { weekday: [2, 0, 1, 2], weekend: [2, 0, 1, 2] },
  "500n": { weekday: [2, 0, 1, 2], weekend: [2, 0, 1, 2] },
};

async function seed() {
  console.log("🚌 Seeding SmartBus AI — BMTC Bangalore (Comprehensive Dataset)");

  console.log("Clearing existing data...");
  await db.delete(busFrequencyTable);
  await db.delete(routeStopsTable);
  await db.delete(busStopsTable);
  await db.delete(busRoutesTable);

  console.log(`Inserting ${stops.length} bus stops across Bangalore...`);
  for (const stop of stops) {
    await db.insert(busStopsTable).values({
      id: stop.id,
      name: stop.name,
      lat: stop.lat,
      lng: stop.lng,
      zone: stop.zone,
    }).onConflictDoNothing();
  }

  console.log(`Inserting ${routes.length} routes (Ordinary, Vajra, Volvo, Airport, Metro Feeder, Night)...`);
  for (const route of routes) {
    // Verify all stops exist before inserting route
    const validStops = route.stops.filter(sid => stops.find(s => s.id === sid));

    await db.insert(busRoutesTable).values({
      id: route.id,
      name: route.name,
      number: route.number,
      from: route.from,
      to: route.to,
      color: route.color,
      totalStops: validStops.length,
      lastBusTime: route.lastBusTime,
      busType: route.busType,
      depot: route.depot,
      distance: route.distance,
    }).onConflictDoNothing();

    for (let i = 0; i < validStops.length; i++) {
      await db.insert(routeStopsTable).values({
        routeId: route.id,
        stopId: validStops[i],
        order: i,
      }).onConflictDoNothing();
    }

    const freq = frequencies[route.id];
    if (freq) {
      await db.insert(busFrequencyTable).values({
        routeId: route.id,
        dayType: "weekday",
        morning: freq.weekday[0],
        afternoon: freq.weekday[1],
        evening: freq.weekday[2],
        night: freq.weekday[3],
      }).onConflictDoNothing();

      await db.insert(busFrequencyTable).values({
        routeId: route.id,
        dayType: "weekend",
        morning: freq.weekend[0],
        afternoon: freq.weekend[1],
        evening: freq.weekend[2],
        night: freq.weekend[3],
      }).onConflictDoNothing();
    }
  }

  const totalBuses = routes.reduce((sum, r) => {
    const stopCount = r.stops.filter(s => stops.find(st => st.id === s)).length;
    return sum + Math.max(2, Math.floor(stopCount / 3));
  }, 0);

  console.log("✅ Seed complete!");
  console.log(`   📍 ${stops.length} bus stops across ${[...new Set(stops.map(s => s.zone))].length} zones`);
  console.log(`   🚌 ${routes.length} routes (${routes.filter(r => r.busType === "Ordinary").length} Ordinary, ${routes.filter(r => r.busType === "Vajra").length} Vajra, ${routes.filter(r => r.busType === "Volvo").length} Volvo, ${routes.filter(r => r.busType === "Airport").length} Airport, ${routes.filter(r => r.busType === "MetroFeeder").length} Metro Feeder, ${routes.filter(r => r.busType === "Night").length} Night)`);
  console.log(`   🚍 ~${totalBuses} simulated live buses`);
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
